name: tensorflow
channels:
  - conda-forge
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit
  - cudnn
  - jupyter
  - notebook
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - numpy
  - opencv
  - pillow
  - pymongo
  - bson
  - xmltodict
  - tqdm
  - scikit-learn-intelex
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - pip
  - pip:
    - tensorflow
    - keras